In [85]:
import numpy as np
import heapq

class Node:
    
    def __init__(self,cost,x,y):
        self.h = cost
        self.x = x
        self.y = y
        self.stepCost = 0
        self.visited = False  
        
    def getCost(self):
        return self.h
    
    def setCost(self,cost):
        self.h = cost
        
        

class PriorityQueue:
    def __init__(self):
        self._queue = []
        self._index = 0
        self.counter = 0

    def push(self, item, priority):
        self.counter += 1
        heapq.heappush(self._queue, (priority, self._index, item))
        self._index += 1
        #print "Pushing number" , self.counter

    def pop(self):
        #print "Elements in stack ",self.counter
        self.counter -= 1
        return heapq.heappop(self._queue)[-1]

    def replace(self,item,priority):
        heapq.heapreplace([item], [priority])
        
    def isEmpty(self):
        if self.counter == 0:
            return True
        else:
            return False

class Board:
    
    def __init__(self,x,y):
        self.x = x
        self.y = y
        self.done = False
        self.matrix = np.zeros((x,y))
        
        self.goal = (0,0)
        
        self.nodeMatrix = {}
        for x_ in range(x):
            for y_ in range(y):
                self.nodeMatrix[x_,y_] = Node(0,x_,y_)
                
        
        self.q = PriorityQueue()

        
        self.correctPath = []
        
        #print self.matrix
        
    def setGoal(self,x,y):
        self.matrix[x,y] = 3
        self.goal = (x,y)
    def makePath(self,path):
        self.setGoal(7,10)
        for tup in path:
            self.matrix[tup[0],tup[1]] = 1 
        print self.matrix
        
    def valid(self,x,y):
        if (-1 < x < self.x):
            if (-1 < y < self.y):
                if self.matrix[x][y] == 0 or self.matrix[x][y] == 3:
                    return True
        
        return False
    
    def lookAtNeighbor(self,x,y,parent):
        
        #print "Looking at ",x,y
        if (-1 < x < self.x):
            if (-1 < y < self.y):
                if self.matrix[x,y] != 1: # This is a wall
                    if self.checkGoal(x,y):
                        self.nodeMatrix[x,y].visited = True
                        score = self.heuristicScore(x,y)
                        n = Node(score,x,y)
                        n.stepCost = parent.stepCost + 1
                        self.nodeMatrix[x,y] = n
                        self.q.push(n,n.h + n.stepCost)
                        self.done = True

                    elif self.matrix[x,y] == 0: # It has not been visited
                        #print "Push", x,y
                        #self.matrix[x,y] = 8
                        self.nodeMatrix[x,y].visited = True
                        score = self.heuristicScore(x,y)
                        n = Node(score,x,y)
                        n.stepCost = parent.stepCost + 1
                        self.nodeMatrix[x,y] = n
                        self.q.push(n,n.h + n.stepCost)


    def addToQue(self,x,y,parent):
        
        self.lookAtNeighbor(x+1,y,parent)
        self.lookAtNeighbor(x-1,y,parent)
        self.lookAtNeighbor(x,y+1,parent)
        self.lookAtNeighbor(x,y-1,parent)

          
    def popOffQueue(self):
        return self.q.pop()
        
    def checkGoal(self,x,y):
        if x == self.goal[0] and y == self.goal[1]:
            return True
        
    def startSearch(self,x,y):
        score = self.heuristicScore(x,y)
        node = Node(score,x,y)
        self.nodeMatrix[x,y] = node
        
        self.q.push(node,score)
        print "Start search"
        
        
        counter = 0
        while not self.q.isEmpty():
            counter += 1
            #print "PoP"
            n = self.popOffQueue()
            self.matrix[n.x,n.y] = 8
            if self.done:
                print "Found goal" 
                break
            else:
                self.addToQue(n.x,n.y,n)
                
            
        
            
    
    def search(self,x,y):
        #print x,y
        

        if self.valid(x,y):
            
            if self.matrix[x,y] == 3:
                print "Goal at" , (x,y)
                return True
            self.matrix[x,y] = -1
            
            
            if self.search(x+1,y):
                print x,y
                return True  
            elif self.search(x-1,y):
                print x,y
                return True  
                
            elif self.search(x,y+1):
                print x,y
                return True  
            elif self.search(x,y-1):
                print x,y
                return True
            else: return False   
  
        else:
            return False
        
    def heuristicScore(self,x,y):
        return abs(x-self.goal[0]) + abs(y - self.goal[1])
            
    def inQueue(self,x,y):
        
        return
    def p(self):
        print "HELLO"

In [86]:
b = Board(8,11)
blocked = [(0,1),(1,1),(3,1),(4,1),(5,1),(6,1),
           (0,3),(2,3),(4,3),(5,3),(6,3),
           (2,4),(4,4),(6,4),
           (0,5),(1,5),(2,5),(4,5),(6,5),(1,7),(3,7),
           (4,7),(5,7),(6,7),(1,8),(3,8),(5,8),(1,9),
           (3,9),(5,9),(6,9),(7,9)
          ]
b.makePath(blocked)

[[ 0.  1.  0.  1.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  1.  0.  1.  1.  1.  0.]
 [ 0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  1.  1.  1.  0.]
 [ 0.  1.  0.  1.  1.  1.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  1.  0.  0.  0.  1.  1.  1.  0.]
 [ 0.  1.  0.  1.  1.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  3.]]


In [87]:
b.startSearch(2,2)


print b.matrix

Start search
Found goal
[[ 0.  1.  0.  1.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  8.  8.  8.  1.  0.  1.  1.  1.  0.]
 [ 0.  8.  8.  1.  1.  1.  8.  8.  8.  8.  8.]
 [ 0.  1.  8.  8.  8.  8.  8.  1.  1.  1.  8.]
 [ 0.  1.  8.  1.  1.  1.  8.  1.  0.  0.  8.]
 [ 0.  1.  8.  1.  0.  8.  8.  1.  1.  1.  8.]
 [ 0.  1.  8.  1.  1.  1.  8.  1.  8.  1.  8.]
 [ 0.  8.  8.  8.  8.  8.  8.  8.  8.  1.  8.]]


In [88]:
b.q.counter

8

In [55]:
c = PriorityQueue()

node_1 = Node(2,1,1)
node_2 = Node(10,1,1)
node_3 = Node(1,1,1)

c.push(node_1,2)
c.push(node_2,10)
c.push(node_3,1)
print c.pop().getCost()
print c.pop().getCost()
print c.pop().getCost()

Pushing number 1
Pushing number 2
Pushing number 3
Elements in stack  3
1
Elements in stack  2
2
Elements in stack  1
10


In [205]:
qq = PriorityQueue()
qq.push(Node(1,2,2),10)

Pushing 1
